"""
NFS-Ganesha build-from-source and export setup for Spectrum Scale (CephCI).

Role model:
  - nfs: node(s) where Ganesha is built/installed (usually installer + mgr)
  - client: NFS test clients (mount only; not used here)

Config defaults match basic-storage-scale-multi-node.sh:
  gerrit_host=github.com
  gerrit_project=nfs-ganesha/nfs-ganesha
  gerrit_refspec=refs/heads/next

Before cmake/rpmbuild, applies scale_acl_fix.patch (setfsuid/setfsgid)
so non-root NFSv4 ACL checks work on GPFS. After install, verifies the
symbol is present in libganesha_nfsd.so.
"""

import shlex

from cli.exceptions import ConfigError, OperationFailedError
from utility.log import Log

log = Log(__name__)

DEFAULT_GERRIT_HOST = "github.com"
DEFAULT_GERRIT_PROJECT = "nfs-ganesha/nfs-ganesha"
DEFAULT_GERRIT_REFSPEC = "refs/heads/next"
DEFAULT_SCALE_FS = "scale_volume"
# Export a subdir — not the FS root — so client rm/cleanup cannot wipe CES/HA dirs.
DEFAULT_NFS_EXPORT = f"/ibm/{DEFAULT_SCALE_FS}/export1"
# IBM Scale ACL fix: setfsuid/setfsgid instead of setresuid/setresgid.
# Without this, non-root NFSv4 ACL checks fail on GPFS-backed Ganesha.
SCALE_ACL_FIX_PATCH_URL = (
    "https://raw.githubusercontent.com/aravindrrh/ci-tests/"
    "scale_downstream/build_scripts/common/scale_acl_fix.patch"
)
MMFS_BIN = "/usr/lpp/mmfs/bin"
# Scale CES materializes CCR-backed Ganesha fragments here.
CES_NFS_CONFIG_DIRS = (
    "/var/mmfs/ces/nfs-config",
    "/var/mmfs/ces/nfs_config",
    "/var/mmfs/nfs_config",
)
# Top-level entry: nfsd.conf already %includes main/log/exports.
CES_NFS_TOP_CONF = "gpfs.ganesha.nfsd.conf"
GANESHA_CONF = "/etc/ganesha/ganesha.conf"

GANESHA_BASE_PACKAGES = (
    "git bison flex cmake gcc-c++ libacl-devel krb5-devel dbus-devel "
    "rpm-build redhat-rpm-config gdb libblkid-devel libcap-devel "
    "libgfapi-devel xfsprogs-devel libnsl2-devel libnfsidmap-devel "
    "libwbclient-devel userspace-rcu-devel libcephfs-devel "
    "selinux-policy-devel sqlite unzip"
)


def _run(node, cmd, timeout=7200, check=True):
    """Run a remote command; raise on non-zero when check=True."""
    log.info("[%s] %s", node.hostname, cmd)
    rc = node.exec_command(cmd=cmd, sudo=True, long_running=True, timeout=timeout)
    if check and rc != 0:
        raise OperationFailedError(
            f"Command failed on {node.hostname} (exit {rc}): {cmd}"
        )
    return rc


def _ensure_scale_ganesha_conf(node, timeout=120):
    """
    Point /etc/ganesha/ganesha.conf at Scale CES NFS config.

    Only %include gpfs.ganesha.nfsd.conf — that file already pulls in
    main/log/exports. Still mmccr fget all gpfs.ganesha*.conf so nested
    includes resolve on disk.
    """
    conf_dir_checks = " ".join(CES_NFS_CONFIG_DIRS)
    top_conf = CES_NFS_TOP_CONF
    script = f"""
set -e
CONF={shlex.quote(GANESHA_CONF)}
MMFS_BIN={shlex.quote(MMFS_BIN)}
TOP_CONF={shlex.quote(top_conf)}
mkdir -p /etc/ganesha

CONF_DIR=""
for d in {conf_dir_checks}; do
  if [ -d "$d" ]; then
    CONF_DIR="$d"
    break
  fi
done
if [ -z "$CONF_DIR" ]; then
  CONF_DIR="/var/mmfs/ces/nfs-config"
  mkdir -p "$CONF_DIR"
fi
echo "Using CES NFS config dir: $CONF_DIR"

# Materialize every gpfs.ganesha* object from CCR (nfsd.conf nests the rest).
echo "----- mmccr flist (ganesha) -----"
CCR_LIST=$("$MMFS_BIN/mmccr" flist 2>/dev/null || "$MMFS_BIN/mmccr" ls 2>/dev/null || true)
echo "$CCR_LIST" | grep -i ganesha || true
while read -r name; do
  [ -z "$name" ] && continue
  case "$name" in
    gpfs.ganesha*.conf) ;;
    *) continue ;;
  esac
  if [ ! -f "$CONF_DIR/$name" ]; then
    echo "mmccr fget $name -> $CONF_DIR/$name"
    "$MMFS_BIN/mmccr" fget "$name" "$CONF_DIR/$name" || \\
      "$MMFS_BIN/mmccr" fget "$name" > "$CONF_DIR/$name" || true
  fi
done < <(echo "$CCR_LIST" | awk '/gpfs\\.ganesha/ {{print $NF}}' | sort -u)

echo "----- ls -la $CONF_DIR -----"
ls -la "$CONF_DIR" || true

if [ ! -f "$CONF_DIR/$TOP_CONF" ]; then
  echo "ERROR: missing $CONF_DIR/$TOP_CONF after mmccr fget" >&2
  exit 1
fi

{{
  echo "# Generated by CephCI — Scale CES entry (nfsd.conf includes the rest)"
  echo "%include $CONF_DIR/$TOP_CONF"
  echo
  echo "NFSv4 {{ Graceless = true; Enforce_utf8_validation = True; }}"
}} > "$CONF"
echo "----- $CONF -----"
cat "$CONF"
"""
    _run(node, f"bash -lc {shlex.quote(script)}", timeout=timeout)


def resolve_ganesha_node(ceph_cluster):
    """Return the primary NFS-Ganesha node (role ``nfs``), fallback to installer."""
    nfs_nodes = ceph_cluster.get_nodes("nfs")
    if nfs_nodes:
        return nfs_nodes[0]
    installers = ceph_cluster.get_nodes("installer")
    if installers:
        log.warning(
            "No node with role 'nfs'; falling back to installer %s",
            installers[0].hostname,
        )
        return installers[0]
    raise ConfigError(
        "Ganesha deploy requires a node with role 'nfs' (or 'installer' fallback)"
    )


def _resolve_git_source(conf):
    """Return (git_url, refspec, local_clone_dir) from config."""
    host = conf.get("gerrit_host", DEFAULT_GERRIT_HOST)
    project = conf.get("gerrit_project", DEFAULT_GERRIT_PROJECT)
    if conf.get("ganesha_repo"):
        repo = conf["ganesha_repo"].rstrip("/")
        if repo.startswith("http://") or repo.startswith("https://"):
            git_url = repo
            project = "/".join(repo.split("/")[-2:])
        else:
            project = repo
            git_url = f"https://{host}/{project}"
    else:
        git_url = f"https://{host}/{project}"

    refspec = (
        conf.get("ganesha_branch")
        or conf.get("gerrit_refspec")
        or DEFAULT_GERRIT_REFSPEC
    )
    git_repo = project.split("/")[-1]
    return git_url, refspec, git_repo


def build_install_ganesha(ceph_cluster, config=None):
    """
    Clone NFS-Ganesha, build RPMs from source, and install on the ``nfs`` node.

    Config keys:
        gerrit_host: git host (default github.com)
        gerrit_project: org/repo (default nfs-ganesha/nfs-ganesha)
        gerrit_refspec: branch/ref (default refs/heads/next)
        ganesha_repo / ganesha_branch: aliases for project URL pieces / refspec
        deploy_timeout: per-command timeout (default 7200)
        yum_repo: if set, install Ganesha from yum instead of source build
    """
    conf = config or {}
    timeout = int(conf.get("deploy_timeout", 7200))
    node = resolve_ganesha_node(ceph_cluster)
    git_url, refspec, git_repo = _resolve_git_source(conf)

    log.info(
        "build_install_ganesha on %s (url=%s refspec=%s)",
        node.hostname,
        git_url,
        refspec,
    )

    # Preflight: rpcbind, SELinux permissive, firewalld off (as in ci-tests script).
    _run(node, "dnf install -y rpcbind || yum install -y rpcbind", timeout=timeout)
    _run(node, "systemctl unmask rpcbind", timeout=timeout, check=False)
    _run(node, "systemctl unmask rpcbind.socket", timeout=timeout, check=False)
    _run(node, "systemctl start rpcbind", timeout=timeout)
    _run(node, "setenforce 0", timeout=60, check=False)
    _run(node, "systemctl stop firewalld || true", timeout=60, check=False)

    yum_repo = conf.get("yum_repo") or conf.get("YUM_REPO")
    if yum_repo:
        _run(
            node,
            "yum-config-manager --add-repo="
            "http://artifacts.ci.centos.org/nfs-ganesha/nightly/libntirpc/"
            "libntirpc-latest.repo",
            timeout=timeout,
            check=False,
        )
        _run(node, f"yum-config-manager --add-repo={yum_repo}", timeout=timeout)
        _run(
            node,
            "dnf -y install nfs-ganesha nfs-ganesha-gluster glusterfs-ganesha",
            timeout=timeout,
        )
        # enable: reboot persistence; start: bring service up now
        _run(node, "systemctl enable --now nfs-ganesha", timeout=timeout)
        return {"ganesha_node": node, "mode": "yum", "yum_repo": yum_repo}

    # Source build path
    _run(
        node,
        "dnf install -y centos-release-gluster yum-utils centos-release-ceph "
        "epel-release unzip --skip-broken || true",
        timeout=timeout,
        check=False,
    )
    _run(
        node,
        "subscription-manager repos --enable "
        "codeready-builder-for-rhel-9-$(arch)-rpms || true",
        timeout=timeout,
        check=False,
    )
    _run(
        node,
        f"dnf install -y {GANESHA_BASE_PACKAGES} --skip-broken",
        timeout=timeout,
        check=False,
    )

    # Fresh clone under /root for a stable path across sudo sessions.
    clone_dir = f"/root/{git_repo}"
    _run(node, f"rm -rf {clone_dir}", timeout=timeout, check=False)
    _run(node, f"git init {clone_dir}", timeout=timeout)
    fetch_script = (
        f"cd {clone_dir} && "
        f'(git fetch --depth=1 "{git_url}" "{refspec}" || '
        f'git fetch "{git_url}" "{refspec}") && '
        "git checkout -B build FETCH_HEAD && "
        "(git submodule update --recursive --init || git submodule sync)"
    )
    _run(node, f"bash -lc {shlex.quote(fetch_script)}", timeout=timeout)

    # Required for non-root ACL tests on Scale; fail hard if context drifted.
    # Dirty working-tree apply is enough — CPack packages the filesystem tree
    # (ci-tests never commits; we verified setfsuid in tarball + installed .so).
    patch_path = "/tmp/scale_acl_fix.patch"
    patch_url_q = shlex.quote(SCALE_ACL_FIX_PATCH_URL)
    patch_path_q = shlex.quote(patch_path)
    patch_script = (
        f"cd {clone_dir} && "
        f"(curl -fsSL -o {patch_path_q} {patch_url_q} || "
        f"wget -q -O {patch_path_q} {patch_url_q}) && "
        f"git apply --verbose {patch_path_q} && "
        "grep -q setfsuid src/os/linux/subr.c"
    )
    log.info(
        "Applying Scale ACL fix patch on %s (setfsuid/setfsgid)", node.hostname
    )
    _run(node, f"bash -lc {shlex.quote(patch_script)}", timeout=timeout)

    # Stop Ganesha only — do not mmces disable nfs (that clears local
    # /var/mmfs/ces/nfs-config while CCR still has the objects).
    _run(node, "systemctl stop nfs-ganesha || true", timeout=timeout, check=False)

    # Same recipe as ci-tests basic-storage-scale.sh (no tarball rewrite —
    # overlaying src/ into the CPack tarball adds a second .spec and breaks
    # rpmbuild -ta with "Found more than one spec file").
    build_script = (
        f"cd {clone_dir} && mkdir -p build && cd build && "
        "cmake -DCMAKE_BUILD_TYPE=Maintainer -DUSE_FSAL_GPFS=ON -DUSE_DBUS=ON "
        "-D_MSPAC_SUPPORT=OFF -DMONITORING=ON -DUSE_MONITORING=ON ../src && "
        "make dist && "
        "tar xOf nfs-ganesha-*.tar.gz --wildcards '*/os/linux/subr.c' "
        "| grep -q setfsuid || "
        "{ echo 'ERROR: setfsuid missing from make dist tarball' >&2; exit 1; } && "
        'rpmbuild -ta --define "_srcrpmdir $PWD" --define "_rpmdir $PWD" *.tar.gz'
    )
    _run(node, f"bash -lc {shlex.quote(build_script)}", timeout=timeout)

    # Purge all IBM gpfs.nfs-ganesha* packages (file conflicts with upstream RPMs).
    remove_script = (
        "pkgs=$(rpm -qa | grep -E '^gpfs\\.nfs-ganesha' || true); "
        'if [ -n "$pkgs" ]; then rpm -e --nodeps $pkgs; fi'
    )
    _run(node, f"bash -lc {shlex.quote(remove_script)}", timeout=timeout)

    # Install from cmake build dir; skip debuginfo/debugsource noise.
    install_script = (
        f"cd {clone_dir}/build && "
        "test -d x86_64 && "
        "rpms=$(find ./x86_64 ./noarch -type f -name '*.rpm' "
        "! -name '*debuginfo*' ! -name '*debugsource*' 2>/dev/null | tr '\\n' ' '); "
        'echo "Installing: $rpms"; '
        'test -n "$rpms" && dnf -y install $rpms'
    )
    _run(node, f"bash -lc {shlex.quote(install_script)}", timeout=timeout)

    # Fail deploy if the installed shared lib still has no setfsuid (patch lost).
    verify_script = (
        "lib=$(ls /lib64/libganesha_nfsd.so* /usr/lib64/libganesha_nfsd.so* "
        "2>/dev/null | head -1); "
        'test -n "$lib" || { echo "ERROR: libganesha_nfsd.so not found" >&2; exit 1; }; '
        'echo "Checking setfsuid in $lib"; '
        'nm -D "$lib" | grep -E "setfsuid|setfsgid" || '
        "{ echo \"ERROR: $lib has no setfsuid/setfsgid - ACL patch not in build\" >&2; "
        "exit 1; }"
    )
    log.info("Verifying Scale ACL fix is present in installed libganesha_nfsd.so")
    _run(node, f"bash -lc {shlex.quote(verify_script)}", timeout=60)

    _run(
        node,
        "sed -i.bak -e 's/^StateDirectory/#&/' "
        "/usr/lib/systemd/system/nfs-ganesha.service || true",
        timeout=60,
        check=False,
    )
    _run(node, "systemctl daemon-reload", timeout=60)
    # enable: unit starts after reboot; start (--now): bring service up for this run.
    # ulimit in this shell does not affect the systemd unit.
    _run(node, "systemctl enable --now nfs-ganesha", timeout=timeout)

    out, _ = node.exec_command(
        cmd="systemctl is-active nfs-ganesha", sudo=True, check_ec=False
    )
    if (out or "").strip() != "active":
        _run(
            node,
            "systemctl status nfs-ganesha --no-pager || true",
            check=False,
        )
        raise OperationFailedError(f"nfs-ganesha not active on {node.hostname}")

    log.info("NFS-Ganesha source build/install completed on %s", node.hostname)
    return {
        "ganesha_node": node,
        "mode": "source",
        "git_url": git_url,
        "refspec": refspec,
        "git_repo": git_repo,
        "clone_dir": clone_dir,
    }


def create_nfs_export(ceph_cluster, config=None):
    """
    Enable CES NFS, add Scale export, apply Ganesha/mmnfs settings, restart service.

    Config keys:
        scale_fs: filesystem name (default scale_volume)
        nfs_export: export path (default /ibm/<scale_fs>/export1)
        deploy_timeout: timeout seconds
    """
    conf = config or {}
    timeout = int(conf.get("deploy_timeout", 7200))
    scale_fs = conf.get("scale_fs", DEFAULT_SCALE_FS)
    nfs_export = conf.get("nfs_export") or (
        DEFAULT_NFS_EXPORT
        if scale_fs == DEFAULT_SCALE_FS
        else f"/ibm/{scale_fs}/export1"
    )
    node = resolve_ganesha_node(ceph_cluster)

    log.info("create_nfs_export on %s export=%s", node.hostname, nfs_export)

    _run(node, f"{MMFS_BIN}/mmces service enable nfs", timeout=timeout)
    _run(
        node,
        f"{MMFS_BIN}/mmuserauth service create "
        "--data-access-method file --type userdefined || true",
        timeout=timeout,
        check=False,
    )
    # Create export subdir on the Scale FS (never export FS root — CES/HA live there).
    # chmod 755: root umask often leaves 750; without other+x, non-root ACL allow
    # tests fail path walk (Permission denied) even with correct file ACEs / setfsuid.
    _run(node, f"mkdir -p {nfs_export} && chmod 755 {nfs_export}", timeout=timeout)
    # Idempotent: reuse path leaves the Scale export in place across runs.
    _run(
        node,
        f"{MMFS_BIN}/mmnfs export add {nfs_export} "
        '-c "*(Access_Type=RW,Squash=none)" || true',
        timeout=timeout,
        check=False,
    )

    _run(node, "systemctl stop nfs-ganesha || true", timeout=timeout, check=False)
    # MINOR_VERSIONS is NFSv4.x only; NFS_PROTOCOLS must include 3 for vers=3 mounts.
    _run(
        node,
        f"{MMFS_BIN}/mmnfs config change NFS_PROTOCOLS=3,4",
        timeout=timeout,
    )
    _run(
        node,
        f"{MMFS_BIN}/mmnfs config change MINOR_VERSIONS=0,1,2",
        timeout=timeout,
    )
    _run(
        node,
        f"{MMFS_BIN}/mmnfs config change ENFORCE_UTF8_VALIDATION=true",
        timeout=timeout,
    )
    # Ensure the export client scope allows v3+v4 (defaults can be v4-only after reuse).
    _run(
        node,
        f"{MMFS_BIN}/mmnfs export change {nfs_export} "
        '-c "*(Access_Type=RW,Squash=none,Protocols=3,4)" || true',
        timeout=timeout,
        check=False,
    )
    # Device/FS name for mmchfs is the Scale FS name, not the export path.
    _run(
        node,
        f"{MMFS_BIN}/mmchfs {scale_fs} -k nfs4 || "
        f"{MMFS_BIN}/mmchfs /ibm/{scale_fs} -k nfs4 || true",
        timeout=timeout,
        check=False,
    )

    # Drop known duplicate line that breaks ganesha restart (ci-tests workaround).
    fixup = (
        "sleep 30; "
        'sed -i.bak -e "41d" /var/mmfs/ces/nfs-config/gpfs.ganesha.main.conf '
        "2>/dev/null || true; "
        'sed -i.bak -e "41d" /var/mmfs/nfs_config/gpfs.ganesha.main.conf '
        "2>/dev/null || true; "
        "sleep 15; systemctl daemon-reload"
    )
    _run(node, f"bash -lc {shlex.quote(fixup)}", timeout=timeout, check=False)

    # Upstream RPM install overwrote stock ganesha.conf; restore Scale CES includes.
    _ensure_scale_ganesha_conf(node, timeout=120)
    # Re-enable in case export-stage restarts dropped the unit link; start service.
    _run(node, "systemctl enable --now nfs-ganesha", timeout=timeout)

    out, _ = node.exec_command(
        cmd="systemctl is-active nfs-ganesha", sudo=True, check_ec=False
    )
    if (out or "").strip() != "active":
        _run(
            node,
            "systemctl status nfs-ganesha --no-pager || "
            "journalctl -u nfs-ganesha --no-pager | tail -80",
            check=False,
        )
        raise OperationFailedError(
            f"nfs-ganesha failed to start after export on {node.hostname}"
        )

    log.info("NFS export ready: %s on %s", nfs_export, node.hostname)
    return {
        "ganesha_node": node,
        "nfs_export": nfs_export,
        "scale_fs": scale_fs,
    }


def deploy_ganesha_stack(ceph_cluster, config=None):
    """Build/install Ganesha then create the Scale-backed export (full NFS stage)."""
    conf = config or {}
    result = {}
    if not conf.get("skip_ganesha"):
        result.update(build_install_ganesha(ceph_cluster, conf))
    else:
        log.info("skip_ganesha set — skipping build/install")
    if not conf.get("skip_export"):
        result.update(create_nfs_export(ceph_cluster, conf))
    else:
        log.info("skip_export set — skipping export create")
    return result
